### ISSUE TITLE
Знайти фото редактора WorPad в Інтернеті 

### ISSUE THREAD

**Issue by veronikaBabiy112** [veronikaBabiy112/PR4#1]
Знайти найкраще фото в Інтернеті

**Comment by tetyana5678** [comment]
Шукаю

**Comment by tetyana5678** [comment]
![image](https://user-images.githubusercontent.com/74248676/98928227-9c68e780-24ea-11eb-9f85-f239b93c6121.png)

**Comment by tetyana5678** [comment]
Знайдено
